Repository rhiroyuki/quotes-api, pull requests merged in 2019-02, with the labels that each got.

#14 Add quote listing endpoint
  app/controllers/quotes-controller.js
  app/models/quote.js
  config/routes/quotes.js
Labels: core-feature

#17 Improve readme
  README.md
  config/environment/production.js
Labels: enhancement

#16 Add swagger doc
  config/routes/index.js
  package-lock.json
  package.json
  swagger.json
Labels: enhancement

#18 Add Travis CI
  .travis.yml
  README.md
  app/controllers/quotes-controller.js
  package.json
  swagger.json
Labels: enhancement

#20 Add an endpoint for deleting a quote
  app/controllers/quotes-controller.js
  config/routes/quotes.js
  swagger.json
Labels: core-feature

#22 Add e2e tests
  .eslintrc.json
  .travis.yml
  config/database.js
  index.js
  package-lock.json
  package.json
  test/e2e/heroku-test.js
  test/e2e/quotes-test.js
  test/e2e/root-test.js
  test/mocha.opts
  test/test_helper.js
Labels: test
